config/routes.rb
Rails.application.routes.draw do

  root 'reviews#index'

  resources :reviews

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/review.rb
class Review < ApplicationRecord

  validates :title, length: { in: 3...255 }
  validates :body, length: { minimum: 10 }
  validates :restaurant, length: { in: 3...255 }
  validates :score, numericality: { only_integer: true, in: 0..10 }

  def to_param
    id.to_s + '-' + title.parameterize(separator: '_')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  def index
    # list all of our reviews
    @number = rand(100)

    # retrieve all review from the db
    @reviews = Review.all    
  end

  def new
    # form for adding new review
    @review = Review.new
  end

  def create
    # take info from the form and add it to the model
    @review = Review.new(review_params)

    # we want to check if the model can be saved
    # if it is, we'll redirect to the home page
    # if it isn't, show the new form
    if @review.save
      redirect_to review_path(@review)
    else
      # show the view for the new.html.erb, with all info
      render action: :new, status: :unprocessable_entity
    end
  end

  def show
    # find individual review from db
    @review = Review.find(params[:id])
  end

  def destroy
    # find the individual review
    @review = Review.find(params[:id])
    # destroy it
    @review.destroy
    # redirect to homepage
    redirect_to root_path
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    # find the review
    @review = Review.find(params[:id])
    # update values
    if @review.update(review_params)
      # redirect to review page
      redirect_to review_path(@review)
    else
      render action: :edit, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review)
      .permit(:title, :body, :score, :restaurant, :ambiance)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for :page_title %> | Bien Review - the best restaurant reviews in the world!</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav>
        <h1>
          <%= link_to root_path do %>
            <%= image_tag 'bien-logo.svg' %>
          <% end %>
        </h1>
      </nav>
      <%# <h1>The best restaurant reviews in the world!</h1> %>
      <nav>
        <%= link_to 'Add new review', new_review_path %>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer>
      Copyright 2022 Bien Reviews
    </footer>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_with model: @review do |f| %>

  <% if @review.errors.any? %>
    <div class="errors">
      <% @review.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :restaurant %>
    <%= f.text_field :restaurant %>
  </p>

  <p>
    <%= f.label :body %>
    <%= f.text_area :body, size: '60x10' %>
  </p>

  <p>
    <%= f.label :score %>
    <%= f.number_field :score, in: 0..10, step: 1 %>
  </p>

  <p>
    <%= f.label :ambiance %>
    <%= f.text_field :ambiance %>
  </p>

  <p>
    <%= f.submit 'Save' %>
  </p>

<% end %>

app/views/reviews/edit.html.erb
<% content_for :page_title, 'Edit restaurant review' %>

<h3>Edit your restaurant review</h3>

<%= render 'form' %>

app/views/reviews/index.html.erb
<% content_for :page_title, 'Latest reviews' %>

<h3>Latest reviews</h3>

<% @reviews.each do |review| %>
  <p class="review">📝 <%= link_to review.title, review_path(review) %> [ <%= review.score %> / 10 ]</p>
<% end %>

app/views/reviews/new.html.erb
<% content_for :page_title, 'Add new restaurant review' %>

<h3>Add your new restaurant review</h3>

<%= render 'form' %>

app/views/reviews/show.html.erb
<% content_for :page_title, @review.title %>

<h3>
  <%= @review.title %>
  [ <%= link_to '✏️', edit_review_path(@review), { title: 'Edit ' + @review.title } %> ]
</h3>

<h4>
  🍝 <%= @review.restaurant %>
  [ <%= @review.score %> out of 10 ]
  <% if @review.ambiance.present? %>
    [ <%= @review.ambiance.capitalize %> ]
  <% end %>
</h4>

<div>
  <%= simple_format @review.body %>
</div>

<div>
  <%= button_to '❌ Delete this review', review_path(@review), method: :delete %>
</div>